### ISSUE TITLE
when user clicks add info on Profile redirect them to same info as signup page

### ISSUE THREAD

**Issue by fcork** [TeamGaiman/thesis#176]

**Comment by parkermuir** [comment]
this was not totally resolved by PR #236 as expected.

I still need to figure out how to handle the CREATE_USER vs UPDATE_USER mutation when reusing the EditUserInfo component since both rely on the button click. Thus right now we still do have duplicate code inside of Signup and EditUserInfo.

**Comment by parkermuir** [comment]
Solution here is to do a conditional usage of the two Mutations depending on which view rendered this component.

**Comment by parkermuir** [comment]
Going to keep these separate for now with potential to revisit.
